### ISSUE TITLE
comboselect.js  里面的$.eAjax 是什么意思？做了封装了吗

### ISSUE THREAD

**Issue by hipos123** [TerryZ/SelectPage#1]
self.prop.xhr = $.eAjax({

**Comment by TerryZ** [comment]
是的，$.eAjax是封装类，这里未删除
但是建议先不要使用Ajax方式的数据源，使用将数据源加载到页面后变成一个Array{Object}格式后，再使用该数据进行初始化操作

Ajax模式的开发完成度并不高

**Comment by TerryZ** [comment]
ajax模式报错的问题在v1.2版本已修复
