### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by netnr** [TerryZ/SelectPage#103]
多选标签时，可以退格键删除标签

`formatItem` 格式化添加图标后，选择时没有图标，但是 `selectPageRefresh` 事件又带上了图标，目前是在选择事件里面调用该事件
```
eSelect: function () {
    $('#tags').selectPageRefresh()
}
```

现在 bootstrap4 ，强制高度 `26px` ，效果不是很好，高度能做成变量配置最好啦

**Comment by TerryZ** [comment]
针对具体平台的兼容处理，建议使用本地化的样式进行适配，通用组件没这个必要也没这个能力对某个具体的 UI 平台做适配

**Comment by netnr** [comment]
样式高度设置 `important` ,增加本地适配难度（如不好全局配置样式覆盖），或可以考虑去除样式高度权重

**Comment by TerryZ** [comment]
实际上样式文件里的多处 `important` 正是当时适配 bootstrap2 与 bootstrap3 的历史遗留产物

**Comment by netnr** [comment]
是的，不过你上下文矛盾了

**Comment by TerryZ** [comment]
不矛盾，正是做过适配，后来有更多的平台也提出适配的需求，才发现这种适配是没意义的
