### ISSUE TITLE
bug一枚，请查收

### ISSUE THREAD

**Issue by a410202049** [TerryZ/SelectPage#11]
```
            $('#select_page').selectPage({
                showField : 'app_key',
                searchField:'keyword',
                keyField : 'id',
                pageSize : 10,
                data : "{{ url_for("admin.ajax_app_page") }}",
                eAjaxSuccess : function(d){
                    var result;
                    if(d) result = d.data;
                    else result = undefined;
                    return result;
                },
                formatItem : function(data){
                    return data.company + '(' + data.app_key + ')';
                }
            });
```
首先代码是没错的，数据都可以得到，数据翻页也是可以正常使用的。目前的问题是，假定数据总共5页，在输入关键词test后，得到新数据有3页，但是点击下一页和最后一页没有任何反应。麻烦作者查看下ajax下是不是有这个bug。
ps：还有一个疑问，如果在ajax分页下，怎么初始化选中呢？
以下是我的后端代码：
def ajax_app_page():
    keyword = request.form.get('keyword','')
    pageNumber = request.form.get('pageNumber', 1, type=int)
    pageSize = request.form.get('pageSize',10,type=int)
    apps_obj = Apps.query.order_by(Apps.create_time.desc())
    apps_obj = apps_obj.filter(Apps.is_del == 0)
    if keyword !='':
        apps_obj = apps_obj.filter(or_(Apps.company.like(u"%{0}%".format(keyword)),Apps.app_key.like(u"%{0}%".format(keyword))))

    paginate = apps_obj.paginate(
        pageNumber, per_page=pageSize, error_out=True)
    apps_items = paginate.items
    apps = []

    for item in apps_items:
        apps.append(item.to_json())

    data = {
        "pageSize":pageSize,
        "pageNumber":pageNumber,
        "totalRow":paginate.total,
        "totalPage":paginate.pages,
        "list":apps
    }
    return CommonResponse(ResultType.Success, message=u"获取成功",data=data).to_json()
排版 好像有点问题 将就看下吧！

**Comment by TerryZ** [comment]
1. 不论是ajax模式还是json数据模式，对控件进行初始化的方式都一样，设置
`<input type='text' id='selectPage' value='10'>`
或  
`<input type='text' id='selectPage' data-init='10'>`
2.ajax查询后的分页，我这里测试暂时没发现问题，你在浏览器里调试一下，首先看看有没有报错，其次，看看查询后的分页，每次向服务端发送的参数是否正常

**Comment by a410202049** [comment]
亲爱的作者，我快崩溃了。昨天按照的你说的方法测试了。ajax后，翻页没有报错。提交的page参数一直为1，在代码1260行，屏蔽了这句话 		//if(q_word.length > 0 && q_word[0]) which_page_num = 1;
可以解决该问题。我知道这句话的意思，每搜索一次会把page置为1。但是点击下一页也会执行这段代码。所以会一直传1.虽然这样做有些不妥。因为会出现一种情况，假设数据为3页，我点到第3页的话，然后再搜索，没有置为1就不会出现数据。然而 ajax初始化 还有问题，虽然代码中有写，                ```
formatItem : function(data){
                    return data.company + '(' + data.app_key + ')';
                }
```
但是初始化后的select 只有 app_key 没有前面的 company和 括号，不知道是不是 showField : 'app_key'的原因导致。

**Comment by TerryZ** [comment]
formatItem 的回调时，具体有没有数据字段，你把data在控制台里打印出来看看不就知道了

**Comment by a410202049** [comment]
//若有查询关键字，则重置当前页码为1 1260行
		if(q_word.length > 0 && q_word[0]) which_page_num = 1;

经过调试，搜索后翻页 本来传的 which_page_num = 2 但是执行到这句 始终都会被置为1。点击下一页，都会执行这个searchForDb ，所以这就是为什么不输入条件是翻页正常，输入了后翻页就一直为1的原因了。

**Comment by TerryZ** [comment]
目前已经重现这个问题，会在近期发个修复版本

btw : 大兄弟，来个star呗

**Comment by a410202049** [comment]
我的哥，已经star了。关键是不带这么坑我好哇。昨天给你提，你说你经过调试没得问题。。。。还有ajax data-init 也有问题啊！不会进               formatItem : function(data){
                    return data.company + '(' + data.app_key + ')';
                }这里面啊。我的哥。项目急需用。麻烦大兄弟修复下。本来我要的效果是 xxxx（key），初始化后直接就是 key。这个也有问题。没问题我吃一斤翔。

**Comment by a410202049** [comment]
还有 	650行的这一句
// $(elem.container).width(orgWidth); 在项目中有个bug屏蔽此处
		$(elem.container).width('100%');
我昨天把所有 有干扰的 css 和js去除。依旧获取不到宽度。目前的解决办法是 100%。这个如果没有问题，我也吃一斤翔！

**Comment by TerryZ** [comment]
不要这么急躁，用不着吃翔，宽度的问题，你要好好检查你的HTML结构是否有继承了父级节点定义的内容

官网DEMO界面，用的就是纯bt3，没有再引入其它任何样式文件，宽度处理并没有问题，宽度会根据父级div的col-md-x的大小来自适应大小

**Comment by a410202049** [comment]
820 行 直接 这样 	$(self.elem.combo_input).val(row[self.option.showField]);设置的 val。当然不会进 formatItem  了。我暂时不慌弄这个了。

**Comment by a410202049** [comment]
坐等 大哥 修复完成。

**Comment by TerryZ** [comment]
最新的v2.5版本，修复了
- ajax模式初始化项目不响应formatItem回调的问题
- 修复ajax模式下输入查询关键字后翻页始终为第一页的问题

初始化功能不能用，我认为，你还是没有仔细阅读DEMO页面第8个实例下面的大段文字说明
其中：
![image](https://user-images.githubusercontent.com/854406/30147088-df4e324a-93ce-11e7-9790-92e1f92487d0.png)
和
![image](https://user-images.githubusercontent.com/854406/30147099-f556354c-93ce-11e7-8793-9654ed9ee328.png)

特地说明了ajax模式下初始化项目需要增加的匹配查询代码，以及前端需要向服务端传递的参数

**Comment by a410202049** [comment]
嗯 亲，我试了下 确实可以了。刚刚比对了下 代码，悄悄的告诉你formatItem确实修复了，但是好像你只修复了多选情况下 没修复单选情况下！ 817行

**Comment by a410202049** [comment]
亲 又有个问题，我初始化的时候 ，点击按钮然后ajax去获取该条数据的data-init，所以就不能一开始在模板里面渲染类似这样<input type='text' id='selectPage' data-init='10'>，所以我在点击按钮得到信息的时候执行    $('#selectPage').val('20');
    $('#selectPage').selectPageRefresh();这种方式，在调用完selectPageRefresh后他没有传searchValue.怎么破？

**Comment by TerryZ** [comment]
你还是没看懂我上面说的话，不论是ajax模式还是json模式，初始化选中值的方式都是：
```html
<input type='text' id='selectPage' value='10,3,4'>
<input type='text' id='selectPage' data-init='10,3,4'>
```
这些必须本身页面就准备好，在json数据模式下，这样设置已经完成了初始选中值的设置
如果是单选模式，插件只会获得第一个ID进行初始化

在ajax模式下，插件需要获得id所对应的完整数据，初始化插件时，插件会向服务端发起查询的请求
向后端请求的参数：
`searchKey`  对应 option.keyField
`searchValue` 对应 设置的value或data-init属性

于是服务端需要获得 `searchKey` 和 `searchValue`两个参数，并生成类似以下的SQL查询语句
```sql
select * from table where searchKey in (searchValue)
```
这个查询并不需要另起服务，只需要在原有的数据查询服务里，增加sql拼接的内容即可，于是对于id的查询和常规数据查询都在同一个服务里

你看看你在服务端是否接收和处理了这两个参数

**Comment by a410202049** [comment]
所以你没懂我意思啊，你说的是页面准备好的情况下。我说的是动态去获取 init-data，在js中动态设置值，然后刚刚阅读了你的代码，存在bug。在770行
`			if(!refresh) {
				$(self.elem.hidden).val(self.option.initRecord);
			}else{
				self.option.initRecord = self.elem.hidden.val()
			}`
这里要把隐藏域的值传给initRecord。不然在 ajax模式里面
`				data: {
						searchTable: self.option.dbTable,
						searchKey: self.option.keyField,
						searchValue: self.option.initRecord
					},`
这里的 elf.option.initRecord 会变成undefined

**Comment by a410202049** [comment]
上面那个问题就是这个原因引起的，就是这个问题我已经解决了。现在还剩最后一个问题。单选模式下formatItem回调问题 麻烦改下呗。

**Comment by TerryZ** [comment]
问题是你何必这样处理页面数据，你的场景应该是编辑表单数据，表单数据的填充是通过ajax获取完成后，再回填到表单中

那么你在做完这个回填的操作，插件的原始input的value不就已经有值了，这时候再去初始化插件即可

不过ajax模式下，动态刷新选中值应该是有BUG，下个版本修复吧

**Comment by TerryZ** [comment]
单选模式下formatItem的问题已经修复了，同样在下个版本上

**Comment by TerryZ** [comment]
v2.6修复了以上全部问题
