### ISSUE TITLE
下拉选项新增功能建议

### ISSUE THREAD

**Issue by MonkSoul** [TerryZ/SelectPage#12]
是否每一个下拉选项可以支持 `描述`文本，也就是下拉选项支持 `标题` + `描述`

**Comment by TerryZ** [comment]
查看文档，使用formatItem回调处理，想怎么格式化就怎么格式化

```js
formatItem : function(data){
    return data.a + '(' + data.b + ')';
}
```

官网DEMO页面里，第3个实例就是这个功能的演示

插件功能较多，也麻烦您先将官网DEMO页面里提供的典型使用案例先看看

感谢反馈！

**Comment by MonkSoul** [comment]
嗯嗯。非常感谢，不好意思，是我这边没有仔细看文档。给您造成麻烦了。
