### ISSUE TITLE
容器高度不足，下拉框向上展开。

### ISSUE THREAD

**Issue by WuRuiLin** [TerryZ/SelectPage#18]
直接在官方在线demo也能重现。将浏览器高度调整小于400也会出现这个问题。该问题在jq插件库也有提问。2017-09-19，下面是附上图

**Comment by WuRuiLin** [comment]
![image](https://user-images.githubusercontent.com/11023015/30623249-f9e35f76-9de8-11e7-8600-9c9737485229.png)

**Comment by TerryZ** [comment]
问题已修复，会在下个版本中更新，请关注插件近期更新

btw：觉得插件还可以，来个Star呗？

**Comment by WuRuiLin** [comment]
好的，谢谢，已经给了星星

**Comment by TerryZ** [comment]
请更新v2.8
