### ISSUE TITLE
选择框内为什么要加一个100px的宽度呢？

### ISSUE THREAD

**Issue by ninestep** [TerryZ/SelectPage#19]
![image](https://user-images.githubusercontent.com/13329058/30998677-f1798b5a-a502-11e7-9883-6e840fa4178c.png)

**Comment by TerryZ** [comment]
插件会获取输入框原始宽度，并将该宽度设置到，否则样式会受影响

**Comment by ninestep** [comment]
![image](https://user-images.githubusercontent.com/13329058/30998847-eca9cd14-a503-11e7-9cbb-fb2ec61d185e.png)
但是他会造成这种情况

**Comment by TerryZ** [comment]
你至少需要对插件的原始input定义好它需要使用的宽度，你这里会出现的100px是浏览器对于input文本框的默认宽度

另外，从你这个截图里看，插件的样式被污染了，插件本身的定义样式内容被UI框架影响

**Comment by ninestep** [comment]
我使用的是bootstrap的栅格系统，我只在父容器里面设置了col-sm-10，如果我直接在input内写宽度的话就破坏了我的自适应了

**Comment by TerryZ** [comment]
使用格栅系统没毛病，但你使用了格栅系统，要对input设置“form-control”，它才会自适应父容器的宽度，看你并没有做一步

**Comment by ninestep** [comment]
![image](https://user-images.githubusercontent.com/13329058/30999254-8d219676-a506-11e7-9cc0-dafc7d4b8c67.png)
![image](https://user-images.githubusercontent.com/13329058/30999260-985d2b90-a506-11e7-8759-192c4eb88270.png)
![image](https://user-images.githubusercontent.com/13329058/30999265-a4144b08-a506-11e7-94f1-92a2c850b0f6.png)
这是我涉及到插件的所有代码，我目前是是使用在input框内直接以style的形式规定宽度来保证我可以继续写功能，但是后期我绝对需要把style删除

**Comment by TerryZ** [comment]
你的input框的父DIV，你设置了“col-sm-12”？？你确定？

**Comment by ninestep** [comment]
![image](https://user-images.githubusercontent.com/13329058/30999505-24e70aee-a508-11e7-93b2-2b8de9a6d303.png)
这个不是？

**Comment by TerryZ** [comment]
我的代码：
![image](https://user-images.githubusercontent.com/854406/30999458-e5a3ba44-a507-11e7-936f-23cf3eee0d9a.png)

![image](https://user-images.githubusercontent.com/854406/30999497-1bb27da0-a508-11e7-8351-ec92201103f0.png)


完全撑满了，没有问题

**Comment by TerryZ** [comment]
首先建议你再重新看一看格栅系统，格栅一行分为12格，你为标题分配了2格，又为输入框分配了12格？那么输入框当然就换行

一行的格栅总数不能超过12格

**Comment by ninestep** [comment]
![image](https://user-images.githubusercontent.com/13329058/30999578-957c320c-a508-11e7-8657-218e3ec5427a.png)
![image](https://user-images.githubusercontent.com/13329058/30999593-abe3b308-a508-11e7-83b3-a638de75d817.png)
我一开始我是直接把栅格删除了，使用设定固定长度的方式。然后为了给你演示重写写错了，而且我的问题不是换行的问题，而是我设定了12格，但是输入框没有把栅格撑满，而是有限的100px，这样我的选项稍微长一点就没办法正常展示，在这张图片里面你应该可以看到这个效果，是绝对不可以的。
上面的图片我没有截最后使用的css，下面的图片我把css截取出来
![image](https://user-images.githubusercontent.com/13329058/30999745-70e62b22-a509-11e7-83ac-e8ea3599bccf.png)

**Comment by TerryZ** [comment]
你先不初始化插件，先看看输入框本身的宽度是否能撑满

**Comment by ninestep** [comment]
![image](https://user-images.githubusercontent.com/13329058/31011981-c6f08e52-a542-11e7-9d91-24b3a6c636d9.png)
![image](https://user-images.githubusercontent.com/13329058/31011997-d47ca48e-a542-11e7-88e2-4fb8907ae2bf.png)
因为你的组件对于我实现功能不是很贴合，所以我更换了组件，无法为你复现，现在我把我其他表单的代码给你贴过来，另外我用的是http://www.zi-han.net/theme/hplus/#的模板

**Comment by TerryZ** [comment]
很遗憾
