### ISSUE TITLE
请问SelectPage如何动态刷新数据源

### ISSUE THREAD

**Issue by 569844962** [TerryZ/SelectPage#2]
目前我需要根据type来进行不同的请求获取不同的数据源，我发现selectPage每初始化一次，就会创建一个。当前动态刷新数据源的方法不？

**Comment by TerryZ** [comment]
插件的数据源建议只做一次性设置，在已初始化完成的情况下再动态改变数据源当前并不支持该功能

由于插件的Ajax数据源的功能并不完善，还在开发中，请暂时先使用json数据源方式先使用，至于你提到的动态修改数据源的功能，敬请关注插件功能更新，也许你提的问题，在下个版本更新时就增加上去了

**Comment by wojiangkai05** [comment]
请问，可以修改当数据清楚出错，优雅的提示方式么，自己修改了但是后续还想使用你的更新。

**Comment by TerryZ** [comment]
好说，目前只是简单粗暴的用Alert来展示信息，ajax数据源的方式还有一些功能要优化，同时信息提示的方式也会以更友好的方式进行展示

敬请关注后续更新

**Comment by TerryZ** [comment]
@569844962 使用$.fn.selectPageData的API动态修改数据源
@wojiangkai05 Ajax的错误提示方式已经去除Alert的方式

敬请更新最新的2.0版本，具体使用实例请访问：
https://terryz.github.io/demo.html
