### ISSUE TITLE
关于清除按钮的显示问题

### ISSUE THREAD

**Issue by hiipeng** [TerryZ/SelectPage#21]
谢谢TerryZ在 v2.7版增加了输入框禁用或只读状态，不显示清除按钮的功能，这个功能我一直想要。但当输入框从禁用变为启用再变为禁用后，清除按钮就一直显示了。建议能不能做一个清除按钮显示的开关，单独控制？

**Comment by TerryZ** [comment]
首先感谢使用插件

你说的问题，其实是属于一个细节处理不到位的地方，会在后续的版本进行完善

而你的建议增加开关来控制这个清除按钮，我个人目前认为没有必要，它应该是一个自动的行为

请关注插件后续版本更新

**Comment by hiipeng** [comment]
ok。谢谢！

**Comment by TerryZ** [comment]
别急着关issues嘛，等解决了你提的问题后，再关不迟

**Comment by TerryZ** [comment]
问题已修复，敬请更新v2.9版本

**Comment by hiipeng** [comment]
谢谢！
Sent from Mail Master
在2017年10月16日 10:08，Terry Zeng 写道： 问题已修复，敬请更新v2.9版本

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TerryZ/SelectPage","title":"TerryZ/SelectPage","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TerryZ/SelectPage"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TerryZ in #21: 问题已修复，敬请更新v2.9版本"}],"action":{"name":"View Issue","url":"https://github.com/TerryZ/SelectPage/issues/21#issuecomment-336762033"}}}
