### ISSUE TITLE
bSelectPage怎么初始化？

### ISSUE THREAD

**Issue by sainaxingxing** [TerryZ/SelectPage#22]
bSelectPage多次调用，会出好多下拉箭头。

**Comment by TerryZ** [comment]
bSelectPage……天哪，你还在用好旧的版本，下载最新的2.8版本吧，同时注意看一下官网的DEMO，初始化入口有调整

**Comment by sainaxingxing** [comment]
哦，这样啊，谢谢回复。小声问下：旧版本没解决方法？或其它写法？我这是旧项目，一换都得换，而且样式也调整了。

**Comment by TerryZ** [comment]
你先尝试新版本吧，有调整只是调用的入口调整和一个参数，功能并没有影响
