### ISSUE TITLE
测试官方的示例发现的问题

### ISSUE THREAD

**Issue by doocal** [TerryZ/SelectPage#23]
官方的示例：
1、点下选择什么也不选。鼠标点一下页面其它地方。此时输入框默认就选种了一个，应该为空。
2、默认获得焦点的控件，圆角成了方角。
3、输入框有图标的，如果选择的文字超过输入框，图标和文档重叠，应该将图标的距离空出来。

**Comment by TerryZ** [comment]
感谢提出意见建议
1.可以根据autoSelectFirst来关闭
2.有意做成这样效果
3.好建议，会尝试解决

**Comment by TerryZ** [comment]
第三点问题，`v2.14` 版本增加了 `dropButton: false` 参数来设置下拉按钮是否显示，对于文字内容会跟清空图标、下拉图标重叠的问题，尽可以优先将输入框的宽度增加
