### ISSUE TITLE
增加 dataFilter 方法

### ISSUE THREAD

**Issue by doocal** [TerryZ/SelectPage#24]
文档只是粗略的看了一下，没发现 dataFilter 这个参数。增加一个给Ajax返回的原始数据的进行预处理的函数，参见 $.ajax 的  dataFilter。 因为好多情况后台返回数据已经固定。只能前端拿到数据后进行预处理(当然自己用$.ajax请求，拿到数据处理后返回给控件也是可以的)。

**Comment by TerryZ** [comment]
callback : eAjaxSuccess

**Comment by doocal** [comment]
OK.
