### ISSUE TITLE
焦点落入 iframe 的时候，控件不能隐藏。

### ISSUE THREAD

**Issue by doocal** [TerryZ/SelectPage#25]
焦点落入 iframe 的时候控件不能隐藏，如果控件下方正好是个文本编辑器或是iframe窗口，控件不能隐藏(一般的操作习惯焦点是直接落入下一个控件的)。

**Comment by TerryZ** [comment]
页面和 iframe 内部是两个不同上下文，且各自独立

以富文本编辑器为例，编辑器内部的任何操作并不会冒泡到上一级，即使编辑器提供了专用的鼠标事件，也仅为具体编辑器的行为，不具备通用性，可行性

基本上没有插件会去着力解决该问题，如果有也是要付出较大代价给每个 iframe 绑定事件

当然，如果有完美解决该问题的方案，欢迎告知
