### ISSUE TITLE
selectpage的一处正则替换问题

### ISSUE THREAD

**Issue by cliff363825** [TerryZ/SelectPage#27]
// data[search][user] -> data[search][user_primary_key]
		if (input_name.match(/\]$/)) input_name = input_name.replace(/\]?$/, namePrefix);
		else input_name += namePrefix;
		if (input_id.match(/\]$/)) input_id = input_id.replace(/\]?$/, namePrefix);
		else input_id += namePrefix;

namePrefix 应该是 namePrefix + "]" 吧

**Comment by TerryZ** [comment]
别在意这里，这里的 id, name 正则替换，后续会移除

**Comment by TerryZ** [comment]
removed on v2.11
