### ISSUE TITLE
searchField 这个字段貌似没用啊

### ISSUE THREAD

**Issue by qetee** [TerryZ/SelectPage#30]
searchField 这个字段根据里应该是在发送ajax请求时，设置搜索内容的请求参数名； 也就是说当searchField: 'query'时；   则后端可以通过query参数获得搜索内容；

实际在2.12中，设置这个值，除了对orderBy有作用外，其他没变化； 而搜索内容的请求参数名则是searchKey

在2.12的代码中，下面这段，完全不知所以然啊，这循环遍历一个写死的，就一个元素的数组是什么鬼？？？？
```
//将参数内容从使用","分隔的字符串转换为数组
var arr = ['searchField'];
for (var i = 0; i < arr.length; i++) {
        option[arr[i]] = this.strToArray(option[arr[i]]);
}
```

真心不知道searchField是做什么用的

**Comment by TerryZ** [comment]
`searchField` 用于设置具体在服务端执行查询的数据字段，没指定的时候，默认使用 `showField` 指定的字段

检查代码发现，有一段向服务端设置 `searchField` 字段的关键代码被上一次执行代码优化时给误删了，导致查询关键字不响应，抱歉

已在最新 `v2.13` 版本修复该问题
