### ISSUE TITLE
功能改进建议

### ISSUE THREAD

**Issue by qetee** [TerryZ/SelectPage#31]
在实际使用中，我需要在发送ajax前，动态设定ajax的请求参数； 举个例子，我有一个table，table的每一行都有一个输入框input:text和一个selectpage； 然后根据当前行的输入框内容，作为selectpage的ajax的参数提交给服务器端后返回selectpage的内容；

在当前selectpage的参数params中，我无法获得当前selectpage控件的dom对象，也就无法匹配到当前表格行的输入框；

另外，希望selectpage增加获取焦点后的事件回调，并在该回调中可以访问控件dom和控件对象本身； 以便于可以动态设置selectpage各项参数；

给params的函数加上参数的方式：

```
var result = _paramsFunc();
```
改成
```
var result = _paramsFunc(this);
```

然后在使用是就可以这样用了
```
params: function(self){
    self.xxx;  
}
```

**Comment by TerryZ** [comment]
首先建议不要指望插件本身提供 dom 内容，只有极少部分的插件会返回或在参数中提供 dom 对象

你写的是一个动态行中的表单处理，建议多用缓存对象的方式来处理；添加新的一行，那么应该是在
 `tbody` 中新增加一行 tr 内容的模板，这个模板可以预先定义在一个隐藏的 div 里，每次新增都从这个隐藏的 div 上去 `clone` 一份，获得 copy 后，将 html 内容变成一个 jquery 对象：var tr = $('<tr>....</tr>');

那么这时候在这个 tr 身上，对里面的各个输入元素进行事件绑定，那么这时候，本身就已经是获得了 tr 这个行的根级 dom 就不需要在操作中再获得

```js
function addRow(){
	...
        //假设 tr 已经是上文中提到，已经 clone 好的行 tr 对象
	var tr = $('<tr>....</tr>');
	var sp = tr.find('input.selectpage'),
		input = tr.find('input.text');
	sp.selectPage({
		keyField: 'id',
		showField: 'name',
		eSelect: function(rowdata){
			input.val(rowdata.id);
		}
	});
	$('table tbody').append(tr);
}
```
以这样的方式，完全不需要插件开放任何 dom 对象出来


不过，经过考虑，还是将插件的内部对象在 `eSelect`、`eOpen`、`eTagRemove`、`eClear` 的回调事件中，增加了 `self` 的参数，该参数是插件的内部对象，即插件内部的 `this`，内容调整在 `v2.13` 中已经添加
