### ISSUE TITLE
控件失去焦点后，如果输入框内有不匹配的选择项的内容，不会自动清空

### ISSUE THREAD

**Issue by qetee** [TerryZ/SelectPage#32]
在2.12中 noResultClean 貌似这个参数又是一个想起作用，但实际却什么作用都没起到的参数；

**Comment by qetee** [comment]
找到原因了

```
if (d.elem.results.find('li').size())
```

这行代码的本意是判断搜索结果是否为空，如果为空，则会到else里清空input内容；但是，实际调试结果是，d.elem.results.find('li').size()的结果永远都不可能为0； 因为当搜索无结果时，d.elem.results.find('li') 会包含一个 li.sp_message_box； 也就是`无查询结果`这个li； 大哥啊，你能不能不要这么坑啊；

用这个插件，简直一步一个坑啊；  这已经不是功能逻辑问题；而是粗心大意了；

**Comment by TerryZ** [comment]
首先非常羞愧于插件的细节处理有这么多毛病，这个问题确实存在，这是在增加一个功能后，对原有功能出现影响的问题。

插件参数太多，交错使用的方式和场景太多，每次新增一个功能或新发布一个版本，会对新增的功能及相关的功能进行测试，每次都进行完整的全功能回归测试，以这点点时间和精力来说，不现实，这也是多数个人开源插件的不足之处

但我会尽可能多做测试，也感谢你多次在使用中提出各种意见和建议，曾经有小兄弟在提 issues 时说自己是小白鼠，语气和心情估计跟你差不多，都说各种踩坑，在此只能再次向你们道歉，给你们工作添麻烦

该问题已在 `v2.13` 中修复
