### ISSUE TITLE
几个小疑问

### ISSUE THREAD

**Issue by yangdq1** [TerryZ/SelectPage#33]
感谢作者这么优秀的控件，初步尝试过程中有几个小疑问：
1.AJAX获取数据时似乎只能是POST；
2.AJAX获取数据时，有最少输入字符数的设置么，超过该长度才去抽取数据？
3.当输入关键词时，自动按空格分段，是否可以关闭此功能的配置，或者自定义分隔符？

谢谢～

**Comment by TerryZ** [comment]
1.POST是向服务端的请求是POST模式，这方面是 get 还是 post 应该影响不大，如果你需要的时话，可以在源码中将 ajax 请求的地方修改成 get 模式
2.对于搜索快速查询，通常没有满足多少长度后，才开始发起搜索的请求，这样不符合交互逻辑，比如大家习惯使用的百度、谷歌，查询的关键字建议也是所有输入都会响应的
3.使用空格对查询关键词进行分组，也是向搜索引擎的使用模式看齐的，你的项目是不是有特殊的需求需要做不一样的处理呢，讨论一下

**Comment by yangdq1** [comment]
谢谢，可能是我的理解有误，个人感觉和搜索引擎还是有些不太一样的，以下主要都是指AJAX方式：
1.POST GET只是建议可以提供属性设置，方便适应各种情况。另外建议指定contentType，或者可配置，（之前统一设为application/json了，这样需要将data转化为JSON.stringify(data)）;
2.因为之前用过一些autocomplete是有这种类似功能的，一般用于请求后台数据时，主要还是考虑性能，避免过多的请求，当然默认是立即响应，只是加一个属性可以设置；
3.因为分组后可能将原先正常的空格分开了，特别是英文单词间，有时并不需要拆开使用，毕竟拆成多个查询起来多多少少影响性能（一般我们项目中只需右模糊匹配，如果拆成多个，需要用in，且左右模糊匹配，是否对索引有影响），即使我在后台重新拼接起来，空格的数量可能不一致了；

前端新手，很多考虑不周，如果不合适就请忽略，谢谢～

**Comment by TerryZ** [comment]
1.不建议你考虑 `post / get` 的问题，`ajax` 方式请求只会以 `json` 的方式进行交互
2.插件参数中已经设置了 `inputDelay` 用于输入延迟，默认 `0.5` 秒，你有需要设置 10 秒都可以
3.关键字查询是模糊查询，并不是完整匹配；当然，在 `ajax` 模式下，会把输入的关键字完整的传递给服务端进行处理，服务端的处理可以自行按需处理一下关键字

**Comment by yangdq1** [comment]
1.ok
2.个人感觉不是一个概念
3.可能我表述的有问题，比如我输入  Shang hai，如果不分词，后台查询查询 where xxx = ‘Shang hai%’，
如果分词后就 必须写成 where xxx like ‘%Shang%’ and  xxx like ‘%hai%’，必须是左右模糊匹配，xxx的索引如果不特殊处理应该会用不到（我记得是这样）

谢谢

**Comment by TerryZ** [comment]
输入延迟查询的配置，就是用于输入完内容后，多久才发起查询，解决的就是频繁查询影响服务器性能，对于这方面的问题解决，基本上没有见过哪一款相关的插件是使用你建议的输入N个关键字后才发起查询，因为这完全不符合使用逻辑

实际上，本地 json 数据处理，对于数据处理已经有了完整的处理逻辑，但 `ajax` 模式，数据处理逻辑完全是交给服务端自行实现，插件仅负责尽可能的向服务端传递足够多的参数和数据，服务端要怎么实现，插件不会干预，也没办法干预，你只需要考虑你想在服务端如何处理查询关键字即可

比如这个所谓的分词，对于 ajax 服务端模式，我想你应该还没具体配置成 ajax 模式进行使用或测试，对于关键字有带空格的，查询的关键字只会保留空格之前的文字，空格之后的内容并不会向服务端传递，另外，完整的输入内容会以 q_word 数组的方式发送给服务端，而数组的内容就是使用空格对内容进行分割后的数组，那么两种参数都完整传递给了服务端，服务端的处理就按照你的需求来处理吧

不过还是很感谢提出你的想法，有你们的意见和建议才能让插件的功能更加完善！

**Comment by yangdq1** [comment]
最少输入还真不是我自己想出来的，之前用select2就有的
ajax模式我有用过，会确实如你所说，会将数组传给后台，就是有个小问题（如果连续多个空格分词后和一个空格是一样的，所以这种情况下后台无法再准确的拼接起来）

当然，这都是很小的点（并不是问题），作者这个select控件真的很优秀，我对比了很多下拉框，只有这款基本都能满足我们的要求，也感谢作者这么及时的回复，祝越来越好，越来越多人使用，谢谢

**Comment by TerryZ** [comment]
满足N个字后才发起查询在功能实现上是极简单的，就是这样的使用交互方式，非常不典型，而且除非业余刚需，否则多数QA就会直接提BUG说这样操作交互不好之类的

使用上有什么问题推荐先上官网上看看DEMO，以及文档，或直接来这里提 issues

**Comment by 317848172** [comment]
请问一下ajax请求数据，请求参数能携带在header里面吗？因为接口调用需要token是需要放在请求头部的

**Comment by TerryZ** [comment]
@317848172 可自行修改源码中的 $.ajax 数据请求部分，增加上头部 token
