### ISSUE TITLE
使用过后一些疑问

### ISSUE THREAD

**Issue by yangdq1** [TerryZ/SelectPage#34]
作者你好，用了之后有点小疑问：

1. autoSelectFirst设置 ajax模式好像不起作用；
2. noResultClean 当已经选中，再去掉部分输入值时，没有自动清除选项

**Comment by TerryZ** [comment]
1.多选 / ajax 模式下，自动关闭
2.确保下载的是 `v2.13` 版本，这个版本有解决了 `noResultClean` 相关的Bug，只要搜索后，结果集是没有匹配项，焦点失去后，会清空

**Comment by yangdq1** [comment]
github上获取最新代码，看注释是2.12，是不是最新的？

**Comment by TerryZ** [comment]
你只需要下载 Master 分支的代码即可，代码注释中的版本号忘记更新了

**Comment by yangdq1** [comment]
那我用的就是最新的了，特别是修改后直接鼠标焦点移开时，并没有清空

**Comment by TerryZ** [comment]
我这里测试，单选和多选功能都正常

**Comment by yangdq1** [comment]
就以官网demo第一个例子为例，输入a后直接鼠标点击其他位置，控件失去焦点值a仍存在

**Comment by TerryZ** [comment]
你还是没理解 `noResultClean` 是什么意思，即是输入的关键字，查询不到任何结果的情况下，清除输入内容

例如，你在官网的第一个DEMO中输入'asdfasdfasdfasdf' 鼠标再移开焦点试试

**Comment by yangdq1** [comment]
那请问如果需求是  未选中任何值 就自动清空  需要如何实现

**Comment by TerryZ** [comment]
暂时没有这样的功能

**Comment by yangdq1** [comment]
好的 谢谢
