### ISSUE TITLE
非常棒的项目，能不能加一个分级的菜单功能

### ISSUE THREAD

**Issue by wmjie** [TerryZ/SelectPage#35]
你好，非常感谢TerryZ的项目，能不能加一个可以分级的下拉菜单功能？
就像这样的：
http://element-cn.eleme.io/#/zh-CN/component/cascader

**Comment by TerryZ** [comment]
插件功能性质，取向并不一样，SelectPage 不会有这些功能

但会在 [SelectMenu](https://github.com/TerryZ/SelectMenu) 上增加的
