### ISSUE TITLE
控件选中值以后，手动删除选中的部分值后，鼠标移出使控件失去焦点，控件显示值未被清空，造成显示不全

### ISSUE THREAD

**Issue by ProdigalWang** [TerryZ/SelectPage#38]
您好！ 在使用了SelectPage之后，我感觉这是一个非常优秀的插件！不过在使用过程中，发现了一些问题想与你探讨！
     在选中下拉框的某个值以后，我删除选中值的一部分后，鼠标移出控件，会有残留的值显示在控件上。请问有计划对这一部分进行改进呢？
      还有就是通过删除键(backspace)手动删除选中的值，而不是通过控件上的 x 删除，是否有回调事件呢？
以上是我遇到的问题，希望您能抽空回答，谢谢！

**Comment by TerryZ** [comment]
那么既然是手动删除，为什么不删除完全一些呢？

**Comment by ProdigalWang** [comment]
即使是手动删完了之后，控件的val()值不是为空，而是存在的？

**Comment by yangdq1** [comment]
我遇到相同的问题，输入部分值焦点移开，界面显示值和实际值无法对应，而我们无法无法控制用户的行为，用户认为是我们写代码问题。另外手工清除好像没有回调接口

**Comment by TerryZ** [comment]
手动清除为什么还需要回调接口呢，没懂
