### ISSUE TITLE
点击右边框的X清除内容后，再输入相同的内容无法将该内容传入后台

### ISSUE THREAD

**Issue by qwer120158285** [TerryZ/SelectPage#40]
比如查询城市
1.输入北京
2.选中北京
3.点击X清除数据
4.再次输入北京
5.后台发现接受的是空字符串。

**Comment by TerryZ** [comment]
所有项目的写值，必须是出现列表项目后，鼠标点击或是键盘选择高亮后回车选择，选中的项目才会被设置到隐藏域中

**Comment by qwer120158285** [comment]
查看了源码，发现clearAll里面没有清除self.prop里面的值，斗胆清除了一下，发现上述问题解决

**Comment by TerryZ** [comment]
这是插件的内部数据对象，不建议处理，我认为你还是操作方式有问题

**Comment by qwer120158285** [comment]
我的问题不是写值的问题，是查询北京，选中后，点击清楚按钮，然后再次输入北京，由于这行代码
if(val && val === self.prop.selected_text) q_word = '';
导致后面输入的北京无法传到后台

**Comment by qwer120158285** [comment]
在clearAll方法中将self.prop.selected_text 和 self.prop.selected_pre两个字段设置为空，就可以正常传值到后台。不知道这里是否是作者有意而为之

**Comment by TerryZ** [comment]
代码会这么写肯定是有其功能需求
对于你描述的问题，我测试了静态数据模式，ajax数据模式，在单选模式下都没有重现你说的查询条件不会传递到服务端的问题

也许是我测试的方式不对
