### ISSUE TITLE
动态修改数据源

### ISSUE THREAD

**Issue by LizhihongJJ** [TerryZ/SelectPage#43]
在项目开发中用到了selectPage,遇到了一个问题，发现官方例子里同样存在这个问题，我在使用动态修改数据源的时候，初始的数据中，点击翻页到最后一页，不选择，点击修改数据源，再点击输入框加载数据为空，再次点击数据更新了。

**Comment by LizhihongJJ** [comment]
大神，什么时候能给看下这个问题呢

**Comment by TerryZ** [comment]
这并不是太大的问题，正常使用下来，不会影响你的工作流转

问题会找时间看，下个升级版本解决

**Comment by TerryZ** [comment]
已在 `v2.18` 版本中修复该问题
