### ISSUE TITLE
显示值有下拉值希望能分开

### ISSUE THREAD

**Issue by qinggan** [TerryZ/SelectPage#45]
![default](https://user-images.githubusercontent.com/9583951/35717791-43ca30d6-081c-11e8-9467-e3384568f3c5.png)

你看，我下拉是树状菜单，我希望显示的时候不显示左边的符号~

**Comment by TerryZ** [comment]
业务逻辑处理的内容，让插件来处理这不是难为插件？

插件已经提供了 `eSelect` 的回调可以允许在选中项目后执行
