### ISSUE TITLE
设置focusDropList为false，输入框获取焦点后还是弹出查询框

### ISSUE THREAD

**Issue by qwer120158285** [TerryZ/SelectPage#46]
文档里面有focusDropList这个属性但是在js中没有找到这个属性。

**Comment by TerryZ** [comment]
这个参数已经不再接受设置，自动启用

如果是希望做成只读表单，点击不弹出列表，只需要在原始 `input` 中添加 `disabled = "disabled"` 属性，将输入框禁用，也可以使用 API ：`$('xxx').selectPageDisabled()` 来禁用

**Comment by qwer120158285** [comment]
厉害。解决！

**Comment by TerryZ** [comment]
壮士能点个 star 或是 follow 再走么，国人普遍不点，不知道是不懂，还是不愿意，无奈
