### ISSUE TITLE
默认值的问题和分页样式名的问题。

### ISSUE THREAD

**Issue by doocal** [TerryZ/SelectPage#48]
1、分页样式名称最好换个默认都是这个名称，就导致还要手工来改样式适配。最好根据插件的特性单独起个名字。
2、源码758-772 行的代码，在使用中发现问题。如果控件的默认值在data 里面找不到，就导致 self.afterInit(self, data);  的 data 参数为空，从而直接导致 afterInit 里面取值报错。 (控件可以手输，可以选择就会产生不一致。或是下拉的数据实际发生变更，都有可能导致控件默认值得和获取数据值不一致。)

如下，如果控件此时有值，值是123就导致 afterInit 内部报错。 

```
var tag_data = [
    {id:1 ,name:'Chicago Bulls',desc:'芝加哥公牛'},
    {id:2 ,name:'Cleveland Cavaliers',desc:'克里夫兰骑士'},
    {id:3 ,name:'Detroit Pistons',desc:'底特律活塞'},
    {id:4 ,name:'Indiana Pacers',desc:'印第安纳步行者'}
];
$('#selectPage').selectPage({
    showField : 'desc',
    keyField : 'id',
    data : tag_data
});
```

**Comment by TerryZ** [comment]
问题均已在 `v2.18` 版本中修复
