### ISSUE TITLE
在使用selectPage 的时候，请问怎么实现关联下拉

### ISSUE THREAD

**Issue by a410202049** [TerryZ/SelectPage#49]
比如有两个下拉框，第一个是省份，第二个是城市。选择了某省份的时候，怎么显示这个省份下的所有城市。不知道怎么触发根据省份id查询城市列表！

**Comment by TerryZ** [comment]
实现其实挺简单，但也许对你的逻辑能力和 js 能力要求较高，假如你想做的是两个 selectpage 之间的联动，你的数据全是页面加载好的 json 数据

1. 省份的列表没什么特别，仅在 `eSelect` 事件中处理选中的项目
2. 城市的列表使用空数据进行初始化
3. 在省份的 `eSelect` 中获得选中省份代码，遍历获得父节点代码是选中项目的城市
4. 使用 `$(城市列表).selectPageData(过滤后的城市列表);` 对城市列表进行刷新

**Comment by a410202049** [comment]
但目前的方式是，两组数据 都是通过ajax到后台查询的。所以我期望的实现方式是，选择了省份之后，触发城市列表组件，传入省份id重新渲染城市列表！不知道目前组件支不支持这个功能？

**Comment by TerryZ** [comment]
不管什么方式都一样，数据源是页面静态的 json 还是服务端返回的 json 本质上没区别，只处理过滤数据的地方一个在 js 端，一个是在服务端就可以处理好，关键是你得想得明白我说的内容

**Comment by a410202049** [comment]
我能够理解你的意思。好的，谢谢你！

**Comment by TerryZ** [comment]
自己先折腾一下，解决不了再说，要是解决了，记得回来 Close

**Comment by a410202049** [comment]
好的！

**Comment by a410202049** [comment]
我已经解决这个问题了               
 params : function(){
                    return {"省份id":"选中后的id"};
                },
把这个参数传给城市列表接口 就可以了！！

**Comment by TerryZ** [comment]
赞！就是这样用
