### ISSUE TITLE
非常棒的下拉页选择器，一个小小的建议

### ISSUE THREAD

**Issue by MonkSoul** [TerryZ/SelectPage#5]
能否推出不依赖 bootstrap 的版本？可以依赖jquery。

**Comment by TerryZ** [comment]
有考虑，实际上插件目前除了严重依赖jQuery，图标上依赖font-awesome之外，其实对bootstrap的依赖并不严重，但要完全脱离于bootstrap肯定要做一定的样式调整

后续会考虑推出一个只依赖normalize.css的版本

**Comment by TerryZ** [comment]
@MonkSoul 
v2.3版本已支持无UI框架环境的支持
引用样式文件select.base.css即可

**Comment by MonkSoul** [comment]
目前大部分管理系统都需要依赖jquery，所以这个不可厚非。不过因为现在UI框架太多，我们是做后端开发的，很少用Bootstrap框架。对于字体图标呢，font-asesome太庞大了。而我们的插件只需要几个图标几个，目前有两个建议：换成 [阿里iconfont](www.iconfont.cn) 这个只需要添加你需要的就可以了。第二个我们可以把拿几个图标弄成小图片）这样依赖也会少很多。


最后，再次感谢您提供这么好下拉框架，目前v2.3已经使用上。非常感谢！

**Comment by TerryZ** [comment]
最新v2.9已移除对font-awesome的依赖！敬请更新
