### ISSUE TITLE
编辑页的级联菜单显示的问题

### ISSUE THREAD

**Issue by tu6ge** [TerryZ/SelectPage#53]
现在级联菜单是可以实现了
但是在已经创建好级联关系的信息上，做编辑页，想把级联菜单默认显示出来，不知道怎么做
现在的情况是只有一级菜单的选中项显示出来了，二级的联动选项有，但是没有在输入框里面显示

**Comment by TerryZ** [comment]
如果是使用 `SelectPage` 和 `SelectPage` 级联，那么，两个元素都需要有各自对应的初始值进行设置

例如 A 选择了浙江省，B 选择了杭州市，A和B两个控件的选中值的对应KEY要被保存，那么在重新加载页面时，将这些KEY依次对应到相应的控件中，设置初始化，即可实现，怎么实现初始化，请阅读官网实例

**Comment by tu6ge** [comment]
我确实是对照文档来做的，我用的服务端数据联动

**Comment by libaidian** [comment]
@tu6ge 你一级菜单是ajax动态的还是写在页面上的？

**Comment by tu6ge** [comment]
ajax动态的
