### ISSUE TITLE
SelectPage默认值问题请教

### ISSUE THREAD

**Issue by libaidian** [TerryZ/SelectPage#54]
在使用SelectPage的时候，可不可以，我传个id进去，在页面渲染的时候默认值就是这个id对应的值啊？

**Comment by TerryZ** [comment]
你应该没看过官网的实例，哪怕一眼

**Comment by libaidian** [comment]
按照官网设置data-init，效果没有出来啊。
html
<input type="text" id="selectpage_office" data-init='8' class="form-control" >

js：
$('#selectpage_office').selectPage({
    showField : 'name',
    keyField : 'id',
    data : "{{ url_for('office_list') }}",
    eAjaxSuccess : function(d){
        var result;
        if(d) result = d.values.gridResult;
        else result = undefined;
        return result;
    }
});


页面：
<div class="sp_container sp_container_open" style="width: 1610px;"><input id="selectpage_office_text" data-init="8" class="form-control sp_input" autocomplete="off" name="selectPage_text" type="text"><input class="sp_hidden" name="selectPage" id="selectpage_office" value="1" type="hidden"><div class="sp_button" title="关闭 (Tab键)"><span class="bs-caret"><span class="caret"></span></span></div><div class="sp_clear_btn" title="清除内容"><i class="iconfont if-close"></i></div></div>

页面上显示的是value=1的值啊

**Comment by libaidian** [comment]
页面代码元素：
<div class="sp_container sp_container_open" style="width: 1610px;"><input id="selectpage_office_text" data-init="8" class="form-control sp_input" autocomplete="off" name="selectPage_text" type="text"><input class="sp_hidden" name="selectPage" id="selectpage_office" value="1" type="hidden"><div class="sp_button" title="关闭 (Tab键)"><span class="bs-caret"><span class="caret"></span></span></div><div class="sp_clear_btn" title="清除内容"><i class="iconfont if-close"></i></div></div>

**Comment by TerryZ** [comment]
再强调一遍，认真阅读官网实例

你的列表应该是没有展示出来，理解 `eAjaxSuccess` 是作什么用的，对于使用 `ajax` 数据源，要怎么使用，要怎么配置，有详细的说明

**Comment by libaidian** [comment]
列表有展示出来，就是每次的哦默认值都是1
