### ISSUE TITLE
服务端数据模式的联动的数据格式问题请教

### ISSUE THREAD

**Issue by libaidian** [TerryZ/SelectPage#55]
var lastProvince = '';
//省份选择器初始化
$('#selectPageProvince').selectPage({
    showField: 'name',
    keyField: 'id',
    data: 'http://aaa.com/loadProvince',
    //选择省份时，清空城市列表已选中的项目
    eSelect: function (data) {
        if(data && lastProvince !== data.id){
            $('#selectPageCity').selectPageClear();
        }
    }
});
//城市选择器的初始化，使用空数据进行初始化
$('#selectPageCity').selectPage({
    showField: 'name',
    keyField: 'id',
    data: 'http://aaa.com/loadCity',
    //向服务端提交的参数中，增加已选中的
    //设置返回-1，意为通知服务端返回空列表，初始化时使用
    params: function(){
        var pv = $('#selectPageProvince').val();
        return {'province': pv?pv:'-1'};
    }
});

'http://aaa.com/loadProvince' 这个返回的数据格式是这么样的？

**Comment by TerryZ** [comment]
你需要使用 `eAjaxSuccess` 参数格式化返回的数据成为数组，学会如何看文档，不要再提问官网已有详细描述的问题
