### ISSUE TITLE
eTagRemove(removeCount)就一个参数？

### ISSUE THREAD

**Issue by Tarems** [TerryZ/SelectPage#56]
能返回被删除的节点信息吗？text和value信息！

**Comment by TerryZ** [comment]
在 `v2.19` 版本中，`eTagRemove` 回调的参数进行了调整

原 removeCount 修改为 datas，叫什么名称是无所谓的，重要的输出的数据从原来的被移除个数，修改为被移除项目的原始数据，即被移除的标签原始的 json 数据
