### ISSUE TITLE
插件实用，赞一个，但是data 改为url的时候，赋值改变选中项时有bug

### ISSUE THREAD

**Issue by yaomy** [TerryZ/SelectPage#57]
插件实用，赞一个，但是data 改为url的时候，赋值改变选中项时有bug；
data直接是数组，是正常的。希望能修复一下，毕竟插件外加一个ajax请求，就缺少灵活性了

**Comment by TerryZ** [comment]
希望你能详细阅读官网实例中对于 `ajax` 数据源的使用方式
