### ISSUE TITLE
cool！可以使用keyfiled进行筛选或定位吗

### ISSUE THREAD

**Issue by neozhu** [TerryZ/SelectPage#58]
如果可以在下拉框中显示2列就更好了。可以实现吗

**Comment by TerryZ** [comment]
设置参数  `formatItem` 可以根据自己的需求拼接，组合内容

btw: 插件不会以表格的形式展示，如果会的话，那应该会以另一个插件的形式出现

**Comment by neozhu** [comment]
可以通过keyfiled筛选吗。因为用户有的时候习惯输入keyvalue，比如单位下拉KG/千克 EA/个 既可以用过EA也可以个来筛选定位

**Comment by TerryZ** [comment]
使用了 `formatItem`  后，就可以根据你自己的组合情况来搜索匹配，例如
```js
formatItem: function(data){
    return data.name + '(' + data.id + ')';
}
```
设置自定义行格式后，输入 name 列的数据或是 id 列的数据都可以进行匹配项目

**Comment by neozhu** [comment]
ok, thank you.
