### ISSUE TITLE
使用建议

### ISSUE THREAD

**Issue by xinmiti** [TerryZ/SelectPage#61]
1，两个SelectPage联动时，两个都是多选模式时，选择第一个SelectPage时第二为弹出的BUG。
2，添加也可以动态设置参数的方法
      比如两个SelectPage联动，第一SelectPage选择1时，第二SelectPage为多选模式。第一SelectPage选择2时，第二SelectPage为单选模式。

**Comment by TerryZ** [comment]
Fixed on last release: `v2.19`
