### ISSUE TITLE
ajax 分页无法初始化显示

### ISSUE THREAD

**Issue by lvjun2015** [TerryZ/SelectPage#68]
请教下作者ajax 分页无法初始化显示的问题

请看截图
![image](https://user-images.githubusercontent.com/16714928/45400161-a1694c80-b67d-11e8-839b-abee7cd9c913.png)

初始化应该是显示 userId 为"613640"，但实际显示的是第一条数据，可以确保初始化数据列表有该数据。

```js
$('#user').selectPage({
	    showField : 'showValue',
	    keyField : 'userId',
	    data : 'ajaxShowUserForSelect.action?cpId=${FO_CP_ID}',
	    eAjaxSuccess : function(d){
	    	console.log(d.selectGrid);
	        return d.selectGrid;
	    },
	    eSelect : function(data){
	    	var bookPersonStr="";
	    	if(""!=data.userId && null!=data.userId){
	    		bookPersonStr=data.userId+","+data.userName;
	    	}
	    	changeBookPerson(bookPersonStr);
	    	$("#bookPerson").val(bookPersonStr);
	    }
	});
```

```html
<div class="base_txtdiv vtip col-md-2  select2me" data-role="jmp" onmouseover="showBookPerson(this);">
          	  <input type="text" id="user" data-init="613640" class="form-control">
          	  <input type="hidden" id="bookPerson">
          </div>
```

找了半天无法查询出原因，特来请教下作者，版本是最新的 `v2.19`

**Comment by TerryZ** [comment]
如果 ajax 模式下，设置了 val 或 data-init 属性，插件会向服务端发起查询项目名称的查询。所以服务端除了需要一个查询数据列表的处理，在这个查询列表的 controller 中还需要增加对初始化时提供的 id 进行查询匹配的项目，这点在官网的 ajax 实例中有详细的描述，你检查一下是不是这个原因

你可以在开发模式下观察网络请求是不是有两个，第一个是查询初始化项目的数据，第二个才是获取数据列表

**Comment by lvjun2015** [comment]
OK 确实是那样，之前一直是定势思维，以为是select下拉那种回写，建议作者在文档那特别标注，估计很多新手可能出现这个问题

**Comment by xiaofuhao** [comment]
谢谢啊！我在这里找到了答案，文档还是没有仔细看清楚，哎 。。。
