### ISSUE TITLE
使用ajax获取数据时，如果不定义eAjaxSuccess就会报错

### ISSUE THREAD

**Issue by firstrose** [TerryZ/SelectPage#71]
如题。我在后端代码直接按照控件要求的格式生成数据。

**Comment by TerryZ** [comment]
使用 ajax 数据源模式，必须设置 `eAjaxSuccess`，如果格式已是按照要求返回，那么在函数里直接
`return data;`

**Comment by firstrose** [comment]
建议给一个默认的return data函数实现，这样，如果格式是按照要求返回的，可以省去一个参数，用起来简单一点。
