### ISSUE TITLE
组件和bootstrap的modal插件不兼容

### ISSUE THREAD

**Issue by firstrose** [TerryZ/SelectPage#73]
在 modal内部放一个selectpage的input，弹出时看不到下拉。

原因是result_area被添加到body的结尾处而不是input后面，实际位置在modal之外，弹出时会被模态框遮住。

我觉得这个不光在bs的模态框上有问题，在原理类似的弹出层组件上面用，应该都会有这个问题。

**Comment by TerryZ** [comment]
自行调整 model 或 SelectPage 的 result_area 容器的 `z-index` 数值，具体环境具体处理
