### ISSUE TITLE
功能很强大，要是能再加入那种根据某些特定场景，比如拼音首字母，分类显示就更赞了，哈

### ISSUE THREAD

**Issue by jhyc** [TerryZ/SelectPage#75]
功能很强大，要是能再加入那种根据某些特定场景，比如拼音首字母，分类显示就更赞了，哈

**Comment by TerryZ** [comment]
既然是分页，就不合适有分组类的功能，但你可以自行组织数据进行分组，比如使用拼音字母首字母做为显示内容的前缀，比如：
```
A - abc手机
B - 奔驰汽车
……
```
