### ISSUE TITLE
能不能在初始化时候也触发一下eSelect事件？

### ISSUE THREAD

**Issue by miwei230** [TerryZ/SelectPage#77]
业务需求，在选中值时，会调用eSelect,但是初始化时，没有钩子函数可以调用。
我想在 SelectPage.prototype.afterInit 后面添加一行（735-745行左右）
 if (p.eSelect && $.isFunction(p.eSelect))
                p.eSelect(row, self);
又怕破坏selectPage的完整性。将来selectPage升级后不好维护。
作者能不能在初始默认值时，加个钩子函数

**Comment by jy-linyu** [comment]
你这个问题是如何解决的呢？我这边也遇到相同的问题了。
