### ISSUE TITLE
能否初始pageNumber参数，分页页码从0开始

### ISSUE THREAD

**Issue by woyuwodao** [TerryZ/SelectPage#81]

**Comment by woyuwodao** [comment]
如题

**Comment by TerryZ** [comment]
不能

**Comment by woyuwodao** [comment]
我加了个参数，可以支持从0开始，默认是从1开始的，在ajax的前后做加减1
pageNumberStartZero : false,

if(p.pageNumberStartZero === true)which_page_num -= 1;
if(p.pageNumberStartZero === true)which_page_num += 1;

**Comment by woyuwodao** [comment]
> 
> 
> 不能
我加了个参数，可以支持从0开始，默认是从1开始的，在ajax的前后做加减1
pageNumberStartZero : false,

if(p.pageNumberStartZero === true)which_page_num -= 1;
if(p.pageNumberStartZero === true)which_page_num += 1;

**Comment by woyuwodao** [comment]
> 
> 
> 不能



我加了个参数，可以支持从0开始，默认是从1开始的，在ajax的前后做加减1
pageNumberStartZero : false,

if(p.pageNumberStartZero === true)which_page_num -= 1;
if(p.pageNumberStartZero === true)which_page_num += 1;

**Comment by TerryZ** [comment]
> > 不能
> 
> 我加了个参数，可以支持从0开始，默认是从1开始的，在ajax的前后做加减1
> pageNumberStartZero : false,
> 
> if(p.pageNumberStartZero === true)which_page_num -= 1;
> if(p.pageNumberStartZero === true)which_page_num += 1;

这种功能需求，你们团队应该优先从服务端进行适配。如果实在只能通过这种方式来解决问题，请下载源码，自行修改使用，这类型不符合常规使用逻辑的需求不会出现在标准产品中

**Comment by woyuwodao** [comment]
> 
> 
> > > 不能
> > 
> > 
> > 我加了个参数，可以支持从0开始，默认是从1开始的，在ajax的前后做加减1
> > pageNumberStartZero : false,
> > if(p.pageNumberStartZero === true)which_page_num -= 1;
> > if(p.pageNumberStartZero === true)which_page_num += 1;
> 
> 这种功能需求，你们团队应该优先从服务端进行适配。如果实在只能通过这种方式来解决问题，请下载源码，自行修改使用，这类型不符合常规使用逻辑的需求不会出现在标准产品中


好的，谢谢！
因为我们的项目都是从0开始的，但好像有一部分公司也是从0开始的
