### ISSUE TITLE
Query - on selectpage UI

### ISSUE THREAD

**Issue by Akshay-Hegde** [TerryZ/SelectPage#82]
Hi, thank you so much for awesome autocomplete plugin, I noticed few things, 
- is there any way to recalculate left and top value of sp_result_area ? example for window resize ( with small screen devices noticed little difficulties while opening and selecting on bootstrap, probably if it is possible to open in modal would be mobile friendly )
- will it be possible to trigger few events for value select and tag close
- will it be possible to have UI feature like v-selectpage as attached below ( searchbox inside result_area and no of items selected, total records indication )
![screenshot from 2019-01-13 22-04-37](https://user-images.githubusercontent.com/7464492/51087911-4fe1e300-177f-11e9-9dbf-d1811caa6824.png)

**Comment by TerryZ** [comment]
1. When document size change(window resize event) SelectPage drop down container layer will auto adjust position again. 
2. Item selected will trigger `eSelect` event, tag remove will trigger `eTagRemove` event, you can checkout the demo in [SelectPage demo7](https://terryz.github.io/selectpage/demo.html)
3. Not yet

**Comment by Akshay-Hegde** [comment]
Thank you so much.
