### ISSUE TITLE
[bug] win10，自带微软输入法无法搜索

### ISSUE THREAD

**Issue by haoranxu1989** [TerryZ/SelectPage#9]
win10系统，自带微软输入法无法搜索，安装第三方输入法可以正常搜索。

tips：切换简体繁体无效。

**Comment by TerryZ** [comment]
经测试，没有该问题
我的环境：windows10 pro 64bit ，输入法：微软拼音，QQ五笔

**Comment by haoranxu1989** [comment]
[http://pan.baidu.com/s/1pLwTlcn](url)

感谢回复，录制了复现bug的gif图片到百度网盘，浏览器打开即可查看。

**Comment by TerryZ** [comment]
http://pan.baidu.com/s/1c2rkb4G

预览图片有错乱的问题，下载了查看就可以看到效果

**Comment by TerryZ** [comment]
![bb](https://user-images.githubusercontent.com/854406/29767949-f64c8128-8c16-11e7-8360-732ff8558ceb.gif)

**Comment by haoranxu1989** [comment]
试了下，谷歌，火狐没问题，IE11复现了该场景。IE版本号：11.576.14393

**Comment by TerryZ** [comment]
抱歉，我使用IE11，即使是文档模式设置到IE8，使用微软拼音也没有这个问题，建议你换一台电脑试试是不是有同样的问题

**Comment by haoranxu1989** [comment]
找到问题了，微软自带的输入法在输入汉字时，在js中空格键keyup无法获取到keycode 32，导致查询失败。最后使用了$(self.elem.combo_input).bind('input propertychange',function(e){}); 来解决微软输入问题。

想问下这样解决是否会带来其他问题。

**Comment by TerryZ** [comment]
我始终也没有办法可以重现你的问题，后面我多试试看看能不能重现吧，如果你急用就自己先改着用
